#!/bin/bash
# ============================================================
#  generate-ssl.sh — Self-Signed SSL Certificate Generator
#  Day 11: CI/CD & Cloud Deployment
# ============================================================
#
#  Academic Insight: SSL Certificates
#  SSL (Secure Sockets Layer) / TLS certificates have two parts:
#    1. Certificate (.crt) — Public, sent to browser
#    2. Private Key (.key)  — Secret, NEVER share
#
#  Types of certificates:
#  - Self-signed: Generated by you (development/demo use)
#    → Browser shows "Not Secure" warning (acceptable for learning)
#  - CA-signed: Signed by a Certificate Authority (DigiCert, etc.)
#    → Browser trusts it (production use, paid)
#  - Let's Encrypt: Free, automated CA certificates (production)
#    → Industry standard for self-hosted apps
#
#  For this project: Self-signed cert (for demo purposes)
#  In production: Use Certbot + Let's Encrypt
# ============================================================

echo "========================================="
echo "  Cineverse SSL Certificate Generator"
echo "  Day 11: CI/CD & Cloud Deployment"
echo "========================================="

# Create ssl directory if it doesn't exist
mkdir -p docker/ssl

# Generate a self-signed SSL certificate
# -x509        → Output a self-signed certificate
# -newkey      → Generate a new private key
# rsa:2048     → RSA key with 2048 bits (secure enough for demo)
# -nodes       → No password on private key (needed for Nginx)
# -days 365    → Valid for 1 year
# -keyout      → Where to save private key
# -out         → Where to save certificate
# -subj        → Certificate subject (organization info)
openssl req -x509 \
  -newkey rsa:2048 \
  -nodes \
  -days 365 \
  -keyout docker/ssl/cineverse.key \
  -out    docker/ssl/cineverse.crt \
  -subj "/C=IN/ST=Maharashtra/L=Mumbai/O=Cineverse/OU=Development/CN=localhost"

echo ""
echo "SSL Certificate generated:"
echo "  Certificate: docker/ssl/cineverse.crt"
echo "  Private Key: docker/ssl/cineverse.key"
echo ""
echo "To use in production:"
echo "  Replace with Let's Encrypt certificate:"
echo "  certbot certonly --webroot -w /var/www/html -d yourdomain.com"
echo ""
echo "IMPORTANT: Never commit cineverse.key to Git!"
echo "Add docker/ssl/*.key to .gitignore"
echo "========================================="
